# плагин упрощает требования к игроку
# если игрок отправляет keepalive, а сервер этого не ждал, плагин сделает так, чтобы за это не кикнуло
# по сути ничего страшного не произошло. цель keep-alive поддерживать соединение, а не разрывать его
name: EasyKeepAlive
main: ua.lokha.easykeepalive.Main
version: "1"
softdepend:
  - ProtocolLib